apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645final
  labels:
    app: survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: student
        image: gmu645/studentsurvey:40
